version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: pass
    #volumes:
    #  - /databases/postgres/findyourbook/data:/var/lib/postgresql/data 
  #glassfish:
    #image: glassfish
    #ports:
    #  - 4848:4848
    #  - 8080:8080
    #volumes:
    #  - ./glassfish:/usr/local/glassfish4
